Delivery Date field was not displaying due to error
Fatal error: Missing Argument 2 for wpdb::prepare() was thrown on the
checkout page, due to which the Delivery Date field was not appearing on
the checkout page. This is fixed now.